"""add_cpe_vendor_to_vendors

Revision ID: e97d5f6a43f6
Revises: 
Create Date: 2026-05-20 15:11:33.072322

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e97d5f6a43f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('cpe_vendor', sa.String(length=255), nullable=True, comment='CPE vendor component for NVD lookup, overrides slug when set'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'cpe_vendor')
    # ### end Alembic commands ###
